### ISSUE TITLE
2.1.1 Inflection bases example tables

### ISSUE THREAD

**Issue by unwitting** [Pomax/nrGrammar#4]
The example tables immediately following the sentence:

> Having covered the "what they look like", let's look at what this means for a number of verbs from both classes, and for verbal adjectives:

both have the heading "五段 verbs" - presumably one was supposed to be "一段 verbs"?

**Comment by Pomax** [comment]
yeah that should have been different headings!

**Comment by unwitting** [comment]
No idea if you actively maintain the book on GH or if it's fixed
as-published?

**Comment by Pomax** [comment]
PRs welcome, it's not at all fixed as published - if enough things get changed, I might simply tell Lightning Resources to put out an updated print copy (benefit of self-publication, although getting new ISBNs is going to be a bit of a hassle since I moved to the other side of the world since last publish =)

**Comment by unwitting** [comment]
Haha, interesting! OK, will raise PRs as appropriate :)

**Comment by Pomax** [comment]
landed =)
