### ISSUE TITLE
2.1.2.1 Particles

### ISSUE THREAD

**Issue by unwitting** [Pomax/nrGrammar#5]
> Moreover, in the Japanese きれいに 分わ ける, translating to the English "to divide cleanly", the に marks the noun きれい, "clean/neat/tidy", as being used adverbially, "neatly, cleanly".

Is きれい not an adjective rather than a noun as the sentence says?

**Comment by Pomax** [comment]
yeah this is a bad example. Thanks for letting me know.

**Comment by Konstantin-Glukhov** [comment]
綺麗	(きれい) is a noun. I don't really see anything wrong with this example.

**Comment by Pomax** [comment]
It's not though, the text is wrong there. According to Japanese grammar, きらい is a 形動, which is a nominal adjective (as opposed to verbal adjective) also called a "な-adjective" because rather than the genetive の that is used for nouns, the adjectival な or the adverbial に gets used. So while the example isn't "wrong", the explanation certainly is.

**Comment by Konstantin-Glukhov** [comment]
Michiel, I was happy to find a book that does not use misnomers like na-adjective, and in my opinion starting using such misnomers will do a great damage to the book. Na-adjective, as you correctly noted in your book "commonly referred to as" one, is not an adjective - it is just an English translation of 形容動詞.  In your book you correctly noted that 形容動詞 require copula in 連体形 to act attributively, on the same account they require adverbial に to act as an adverbial modifier. There is no reason to call 形容動詞 na-adjective.  Again, as you correctly mentioned in your book, some nouns in English can be used attributively, e.g. "constant diarrhea", and some cannot be used attributively without undergoing part of speech transformation, e.g. day (n) -> daily (adj) "daily diarrhea".  The fact that nouns can be used attributively does not justify to call them any kind of adjectives. Adjective is a part of speech, attribute is a part of a sentence. A simple fact of using a part of speech in a sentence attributively does not turn it into an adjective.

**Comment by Pomax** [comment]
Which is why I gave you the Japanese grammatical term first. It's not a noun in Japanese, Grammars and dictionaries classify it as a 形動, best translated as a nominal adjective, because that's what it is: a word that in isolation can be can be considered, linguistically, as noun, but when used in grammatical roles acts, linguistically, as an adjective. Don't fall in the trap of word classification: an nominal adjective is, at its core, an adjective, which does not inflect when used on its own, and thus acts similar to a noun, until we try to tack particles onto it, at which point it's incredibly clear this is not a true noun in the linguistic sense.

**Comment by Konstantin-Glukhov** [comment]
Unfortunately the linguistic terms are used loosely but it does not justify to use them incorrectly. Adjective is a part of speech, and as you mentioned a word on its own is qualified as a part of speech: noun, adjective, verb, adverb, etc. In the context of a sentence different terminology is used: subject, predicate, object, attribute, adverbial modifier. Statement "used as an adjective" is semantically incorrect.  A part of speech, including adjective, can be "used as an attribute". If one should describe 形動 (short for 形容動詞) by its role in a sentence then it should be referred as Na-attribute and in no way as Na-adjective. And let's be serious here: how childish it is to say "best translated"?  Who decided that this is "best"? :) In my humble opinion 形容動詞 is a noun: it has all attributes of a noun (part of speech) and is used in a sentence the same way nouns are used (as attribute, subject, and as part of complex predicate).

If you want to call an attribute an adjective - it is your choice, but it is not how it is defined in English grammar.

**Comment by Pomax** [comment]
Then I guess we'll just disagree on this issue. As far as my linguistics training goes, this word is grammatically correctly classified as a nominal adjective, and can be found in roles that overlap with true nouns.

**Comment by Konstantin-Glukhov** [comment]
了解

**Comment by Konstantin-Glukhov** [comment]
https://en.wikipedia.org/wiki/Adjectival_noun_(Japanese)

**Comment by Konstantin-Glukhov** [comment]
http://japanese.stackexchange.com/questions/1008/why-does-japanese-have-two-kinds-of-adjectives-i-adjectives-and-na-adjective/1016#1016

http://japanese.stackexchange.com/questions/920/why-is-it-that-some-%e5%bd%a2%e5%ae%b9%e5%8b%95%e8%a9%9e-accepts-%e3%81%ae-after-it-while-some-only-accepts-%e3%81%aa-after-it

**Comment by k3zi** [comment]
Noticed this was still open. I know its more of a personal preference, but the point I see in using words like "noun" and "adjective" are to help people relate back to their own language. But in a language where "noun" and "adjective" don't always describe what they originally meant, it serves to sever that connection. The last thing we would possible want to come into fruition is: another book that gives these 形容動詞 their own conjugations when they are not modifying before a nominal. A small fraction of books actually make reference to this, and the rest bloat the language with more constructs. The book I learned from by noted Japanese linguist, Eleanor Jorden, used the terms nominals, and na-nominals. The main point I picked up on was that language acquisition should't be don in the context of your own language, because doing so can make the target language harder to grasp.
